app:
  general:
    logger:
      trace: traceLogger
      error: errorLogger
      performance: performanceLogger
      serviceIP: localhost
      logPath: "D:/WorkStation/system-bk/auth_logging/"
spring:
  application:
    name: system-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/AUTH
    username: postgres
    password: 123456
  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    user:
      name: admin
      password: admin
server:
  port: 2001

jwt:
  expTime: 1080 # 18 min
  secret: DataCore321
