app:
  general:
    logger:
      trace: traceLogger
      error: errorLogger
      performance: performanceLogger
      serviceIP: localhost
      logPath: "D:/WorkStation/system-bk/auth_logging/"
spring:
  application:
    name: system-service
  datasource:
    url: jdbc:postgresql://localhost:5432/AUTH
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
server:
  port: 2001

jwt:
  expTime: 300 # 18 min
  secret: DataCore321

springdoc:
  swagger-ui:
    path: /open-api
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: list
    display-request-duration: true
    filter: false
    show-extensions: true
    disable-swagger-default-url: true
